[package]
name = "l3"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
aws-config = "1.5.9"
aws-sdk-apigatewayv2 = "1.48.0"
aws-sdk-iam = "1.50.0"
aws-sdk-lambda = "1.53.0"
base64 = "0.22.1"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
lazy_static = "1.5.0"
notify = { version = "7.0.0", default-features = false, features = ["macos_fsevent"] }
regex = "1.11.1"
serde_json = "1.0.132"
sha2 = "0.10.8"
swc = "4.0.0"
swc_common = { version = "3.0.0", features = ["concurrent"] }
swc_ecma_ast = "3.0.0"
swc_ecma_parser = { version = "4.0.0", features = ["typescript"] }
tokio = { version = "1.41.0", features = ["full"] }
toml = "0.8.19"
yaml-rust = "0.4.5"
zip = "2.2.0"

[dev-dependencies]
temp-dir = "0.1.14"
