[package]
name = "l3"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
aws-config = "1.5.0"
aws-sdk-apigatewayv2 = "1.28.0"
aws-sdk-iam = "1.29.0"
aws-sdk-lambda = "1.29.0"
base64 = "0.22.1"
clap = { version = "4.5.4", features = ["derive"] }
sha2 = "0.10.8"
swc = "0.278.0"
swc_common = "0.34.2"
swc_ecma_ast = "0.115.1"
swc_ecma_parser = "0.146.2"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.13"
yaml-rust = "0.4.5"
zip = "2.1.2"

[dev-dependencies]
temp-dir = "0.1.13"
