[package]
name = "l3"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
aws-config = "0.55.1"
aws-sdk-lambda = "0.26.0"
base64 = "0.21.0"
clap = { version = "4.1.14", features = ["derive"] }
sha2 = "0.10.6"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
zip = "0.6.4"

[dev-dependencies]
temp-dir = "0.1.11"
