[package]
name = "l3"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
aws-config = "1.2.0"
aws-sdk-iam = "1.21.0"
aws-sdk-lambda = "1.21.0"
base64 = "0.22.0"
clap = { version = "4.5.4", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
zip = "0.6.6"

[dev-dependencies]
temp-dir = "0.1.13"
