[package]
name = "l3"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
aws-config = "1.5.3"
aws-sdk-apigatewayv2 = "1.33.0"
aws-sdk-iam = "1.34.0"
aws-sdk-lambda = "1.34.0"
base64 = "0.22.1"
clap = { version = "4.5.8", features = ["derive"] }
crossterm = "0.27.0"
lazy_static = "1.5.0"
regex = "1.10.5"
sha2 = "0.10.8"
swc = "0.279.0"
swc_common = "0.34.3"
swc_ecma_ast = "0.115.1"
swc_ecma_parser = "0.146.7"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
yaml-rust = "0.4.5"
zip = "2.1.3"

[dev-dependencies]
temp-dir = "0.1.13"
