# config for https://github.com/crate-ci/cargo-release

tag-message = "cargo release {{tag_name}}"
pre-release-commit-message = "cargo release"

pre-release-replacements = [
    { file = "CHANGELOG.md", search = "^## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] - {{date}}", exactly = 1,  prerelease = false },

    # for subsequent releases
    { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", min = 0, max = 1,  prerelease = false },

    # for initial and subsequent releases
    { file = "CHANGELOG.md", search = "^\\[Unreleased\\]", replace = "[Unreleased]: https://github.com/eighty4/l3/compare/{{tag_name}}...HEAD\n[{{version}}]", exactly = 1,  prerelease = false },

    # for initial releases
    { file = "CHANGELOG.md", search = "https://github.com/eighty4/l3/commits/main$", replace = "https://github.com/eighty4/l3/releases/tag/{{tag_name}}", min = 0, max = 1, prerelease = false },
]
