[package]
name = "l3_api_base"
version = "0.0.1"
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
name = "l3_api_base"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
