name: Release upload
run-name: Upload ${{ inputs.filename }} to release ${{ inputs.tag_name }}

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      release_id:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      upload_hostname:
        required: true
        type: string

jobs:

  publish-asset:
    name: "publish ${{ inputs.filename}}"
    runs-on: ubuntu-latest
    env:
      FILENAME: ${{ inputs.filename }}
      RELEASE_ID: ${{ inputs.release_id }}
      UPLOAD_HOSTNAME: ${{ inputs.upload_hostname }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.filename }}
          path: ${{ inputs.filename }}
      - name: upload
        run: |
          curl --fail --silent -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: $(file $FILENAME -b --mime-type)" \
            https://$UPLOAD_HOSTNAME/repos/eighty4/l3/releases/$RELEASE_ID/assets?name=$FILENAME \
            --data-binary "@$FILENAME"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
