name: l3 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --all-features
      - run: cargo test
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -v
      - run: git diff --exit-code
