name: Upload

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      target:
        required: true
        type: string
      release_id:
        required: true
        type: string
      upload_hostname:
        required: true
        type: string

jobs:

  upload-gh-asset:
    runs-on: ubuntu-22.04
    env:
      FILENAME: ${{ inputs.filename }}
      TARGET: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: build
        run: |
          rustup target add $TARGET
          cross build --release --target $TARGET
          mv target/$TARGET/release/l3 $FILENAME
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          RELEASE_ID: ${{inputs.release_id}}
          UPLOAD_HOSTNAME: ${{inputs.upload_hostname}}
      - name: upload
        run: |
          curl --fail --silent -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: $(file $FILENAME -b --mime-type)" \
            https://$UPLOAD_HOSTNAME/repos/eighty4/l3/releases/$RELEASE_ID/assets?name=$FILENAME \
            --data-binary "@$FILENAME"
