name: Verify

on:
  push:
    branches: [ '*' ]
    paths:
      - .github/workflows/verify.yml
      - fn_*/**/*
      - l3_*/**/*
      - Cargo.*
  pull_request:
    branches: [ '*' ]
  workflow_call:
  workflow_dispatch:

jobs:

  verify:
    runs-on: ubuntu-latest
    needs:
      - build-l3-cli-linux-and-macos
      - build-l3-cli-windows
      - build-l3-fn-build-wasm
      - examples
      - fmt
      - lint
      - test
      - test-fixtures-linux
      - test-fixtures-osx-win
    steps:
      - run: echo "We're gonna face it"

  build-l3-cli-linux-and-macos:
    name: "build ${{ matrix.filename}}"
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - filename: l3-linux-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - filename: l3-linux-aarch64
            runner: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            apt_package_linker: gcc-aarch64-linux-gnu
          - filename: l3-macos-x86_64
            runner: macos-latest
            target: x86_64-apple-darwin
          - filename: l3-macos-aarch64
            runner: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.apt_package_linker }}
        run: |
          sudo apt update && sudo apt install ${{ matrix.apt_package_linker }}
          mkdir -p $HOME/.cargo
          mv ./.github/workflows/linkers.toml $HOME/.cargo/config.toml
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - run: rustup target add ${{ matrix.target }}
      - name: build
        run: cargo build --locked --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.filename }}
          path: target/${{ matrix.target }}/release/l3

  build-l3-cli-windows:
    name: "build ${{ matrix.filename}}"
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - filename: l3-windows-aarch64.exe
            target: aarch64-pc-windows-msvc
          - filename: l3-windows-x86_64.exe
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - run: rustup target add  ${{ matrix.target }}
      - name: build
        shell: powershell
        run: cargo build -p l3_cli --locked --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.filename }}
          path: target/${{ matrix.target }}/release/l3.exe

  build-l3-fn-build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - run: rustup target add wasm32-wasip2
      - name: cargo build
        run: cargo build --all-features --locked --release -p l3_fn_build_wasm --target wasm32-wasip2
      - uses: actions/upload-artifact@v4
        with:
          name: l3-fn-build.wasm
          path: target/wasm32-wasip2/release/l3_fn_build.wasm

  examples:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - name: cargo build
        run: |
          cargo run --example build_fn
          cargo run --example parse_fn
        working-directory: fn_build

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - name: cargo fmt
        run: cargo fmt --all -v
      - run: git diff --exit-code

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - name: clippy
        run: |
          cargo clippy --all -- -D warnings
          cargo clippy --all --tests -- -D warnings
        if: github.ref == 'refs/heads/main'
      - name: clippy
        run: |
          cargo clippy --all
          cargo clippy --all --tests
        if: github.ref != 'refs/heads/main'
        continue-on-error: true

  test:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        runs_on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - name: cargo test
        env:
          SKIP_BUILD_FIXTURES: true
        run: cargo test --workspace

  test-fixtures-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - name: nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. ~/.nvm/nvm.sh
          nvm install 18
          nvm install 20
          nvm install 22
          nvm install 24
      - name: cargo test
        run: cargo test -p l3_fn_build testing

  test-fixtures-osx-win:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        runs_on: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - name: cargo test
        env:
          SKIP_NVM: true
        run: cargo test -p l3_fn_build testing

  test-cli-build:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        runs_on: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - run: cargo install --path l3_cli
      - run: l3 build --release
        working-directory: fn_config/fixtures/project_toml_lambdas/explicit_lambda
